url: ""
baseurl: ""
title: "FIVE-LINK"
description: > # this means to ignore newlines until "baseurl:"
  Five-Link is changing stay tuned.<br>Beta 0.6.
email: fivelink@outlook.com
markdown: kramdown

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
