url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title: Five-Link
email: five-link@outlook.com
author: GitHub User

description: >- # this means to ignore newlines until "baseurl:"
  Ideas to explore in sport, technlogy and art.


favicon: "/images/drawing_03.svg"


google_analytics: google.com, pub-8613892269045774, DIRECT, f08c47fec0942fa0

navigation:
  - text: Home
    url: /
  - text: About
    url: /about/


markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  


brand_color: "#ea25af"
theme_color: "#090a0b"
