
title: FIVE-LINK
email: fivelink@outlook.com
description: > # this means to ignore newlines until "baseurl:"
 Five-Link offers five links to some of the most interesting topics around the web that will hopefully inspire and encourage you on your journey. Thank you you for visiting.<br>Beta 0.4.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://five-link.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
