url: ""
baseurl: ""
title: "FIVE-LINK"
description: > # this means to ignore newlines until "baseurl:"
  Five-link is an exploration of ideas and culture from around the web. Thank you for visiting.
email: fivelink@outlook.com
markdown: kramdown

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
