# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Five-Link
email: fivelink@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Five-Link offers five links to some of the most interesting topics around the web that will hopefully inspire and encourage you. Thank you for visiting.<br>Beta 0.5.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown


defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
