url: ""
baseurl: ""
title: "FIVE-LINK"
description: > # this means to ignore newlines until "baseurl:"
  Five-Link offers links to some of the most interesting topics around the web that will hopefully inspire and encourage you. Thank you for visiting.<br>Beta 0.6.
email: fivelink@outlook.com
markdown: kramdown

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
