
title: FIVE-LINK
email:
description: > # this means to ignore newlines until "baseurl:"
  I will be posting links to articles here that I find interesting and useful and hopefully you will as well.
  I will also be writing short rough essays on certain subjects in the news and articles that I have posted links to.
  .Beta 0.02.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://five-link.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
