title: Five-Link
email: fivelink@outlook.com
description: >
  Five-Link offers five links to some of the most interesting topics around the web that will hopefully inspire and encourage you and a few blog posts. Thank you for visiting.
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
